### ISSUE TITLE
Benchmarking the library

### ISSUE THREAD

**Issue by petevine** [ptitSeb/gl4es#13]
I've recently started compiling glshim/gl4es with `LTO` and compared to a normally built glshim's `libGL` (ca. 520kB) it comes out at 620-700 kB depending on gcc version. (probably lots of inlining)

It would be great to actually check which optimizations help/hurt performance and whether the increased size incurs any penalty. 

Might the library be benchmarked excluding other factors like X or GLES drivers?

CC: @lunixbochs

**Comment by petevine** [comment]
cc: @lunixbochs

**Comment by ptitSeb** [comment]
I don't see any practical way of benchmarking without taking into account underlying X or GLES.
But if the bench is conducted on the machine, just switch libGL version, it should be representative.

Main point is also how to bench. There are not a lot of opensource synthetic benchmark using GL1.5 only, so it's better to rely on game.
If fps can be "recorded" with LIBGL_FPS, not many games have an integrated benchmark function, so the benchamark will relly on a lot of manual "timming". 
The Quake engine game (at least 2 and 3) have an integrated "Timedemo" that can be used. Not sure if anything else.

**Comment by lunixbochs** [comment]
just use apitrace a few games at the OpenGL layer and replay into glshim for benchmarks. note the numbers will be hardware-specific. this can be done automatically for both functionality and performance regressions.

**Comment by ptitSeb** [comment]
Good idea. I guess the replay function doesn't try to do any kind of vsync or respect initial timing?

**Comment by petevine** [comment]
@ptitSeb  I've just tried using `apitrace trace`, and managed to `capture/replay` glxgears and torcs that use X directly but SDL games fail to start. Replay doesn't work with `gl4es`:

```shell
LIBGL: ERROR: EGL Error detected: EGL_BAD_MATCH (0x3009)
error: failed to make current OpenGL context and drawable
````

**Comment by ptitSeb** [comment]
Can you try with LIBGL_FB=1 maybe?

**Comment by petevine** [comment]
The error message came from trying to run `apitrace replay` whereas running SDL apps just terminates silently (with or without glshim) leaving a nascent trace. 

I'm probably going to rebuild `apitrace` with debug enabled.

**Comment by ptitSeb** [comment]
Yep. And running
`LIBGL_FB=1 apitrace replay`
doesn't help?

**Comment by petevine** [comment]
On Tue, 08 Nov 2016 06:46:34 -0800
ptitSeb <notifications@github.com> wrote:

> Yep. And running
> `LIBGL_FB=1 apitrace replay`
> doesn't help?

Nope :) Same error.

**Comment by ptitSeb** [comment]
Ah :( I need to debug that.

**Comment by petevine** [comment]
Well, debug didn't add much but verbose output (`-v`) says this:

```shell
$ apitrace replay -v glxgears.5.trace 
LIBGL: Initialising gl4es
LIBGL: v0.9.2 built on Nov  7 2016 20:33:06
LIBGL:loaded: libGLESv1_CM.so
LIBGL:loaded: libEGL.so
LIBGL: Extension GL_OES_point_sprite detected and used
LIBGL: Extension GL_OES_point_size_array detected
LIBGL: Extension GL_OES_framebuffer_object detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Max texture size: 4096
LIBGL: Texture Units: 8, Max lights: 8
LIBGL: Implementation Read is GL_RGB/GL_UNSIGNED_SHORT_5_6_5
LIBGL: Current folder is:/home/odroid
1 @0 glXCreateContext(dpy = 0x44170, vis = &{visual = 0x4e320, visualid = 33, screen = 0, depth = 16, c_class = 4, red_mask = 63488, green_mask = 2016, blue_mask = 31, colormap_size = 64, bits_per_rgb = 8}, shareList = NULL, direct = True) = 0x4ec50
2 @0 glXMakeCurrent(dpy = 0x44170, drawable = 39845890, ctx = 0x4ec50) = True
LIBGL: ERROR: EGL Error detected: EGL_BAD_MATCH (0x3009)
error: failed to make current OpenGL context and drawable
````

**Comment by ptitSeb** [comment]
Ok, looks clean. I have to check why I get BadMatch...

**Comment by ptitSeb** [comment]
Ok, I cannot reproduce the issue on my side.
I tried to improve things, but I may have make things worse. It's: 4e0c72132379c5f027f0030de7114a77b8d93a73

Please test.
To help diagnosis, also, look at https://github.com/ptitSeb/gl4es/blob/4e0c72132379c5f027f0030de7114a77b8d93a73/src/glx/glx.c#L30
uncomment that to have more verbose message on gl4es side. It can also help pinpoint the issue.

**Comment by petevine** [comment]
That produced the following new info:

```shell
glXQueryVersion(0x521900, 0xbe8decd0, 0xbe8decd4)
glXQuesryExtension(0x521900, 0x516008, 0x51600c)
glXQueryExtensionString(0x521900, 0)
1 @0 glXCreateContext(dpy = 0x44170, vis = &{visual = 0x4e320, visualid = 33, screen = 0, depth = 16, c_class = 4, red_mask = 63488, green_mask = 2016, blue_mask = 31, colormap_size = 64, bits_per_rgb = 8}, shareList = NULL, direct = True) = 0x4ec50
glXChooseFBConfig(0x521900, 0, 0x57d6b8, 0xbe8debac)
glXGetVisualFromFBConfig(0x521900, 0xb2b08ef8)
glXCreateContextAttribsARB(0x521900, 0xb2b08ef8, (nil), 1) config is RGBA:8888, depth=1, stencil=1, drawable=1
2 @0 glXMakeCurrent(dpy = 0x44170, drawable = 39845890, ctx = 0x4ec50) = True
glXCreateWindow(0x521900, 0xb2b08ef8, 37748738, (nil))
glXMakeCurrent(0x521900, 0x2400002, 0x57d6a0) 'isPBuffer(drawable)=0
LIBGL: ERROR: EGL Error detected: EGL_BAD_MATCH (0x3009)
error: failed to make current OpenGL context and drawable
````

I wonder if running manually via `LD_PRELOAD` could help?

**Comment by petevine** [comment]
[glxgears.5.trace.txt](https://github.com/ptitSeb/gl4es/files/580519/glxgears.5.trace.txt)

**Comment by ptitSeb** [comment]
Ok, thanks. So glXCreateContext is in fact not called... Mmmm, I have to think about it, but the call made to glX are not at all the one printed by apitrace...

**Comment by petevine** [comment]
BTW, didn't notice the latest revision didn't work at all :)

**Comment by ptitSeb** [comment]
There is issue with SDL stuff only or most things? I only tested glxgears on my side.

**Comment by petevine** [comment]
Tried a few things, most didn't work - glxgears was showing a black screen with `egl bad window` scrolling on the console.

**Comment by ptitSeb** [comment]
Yeah mean, with the last update, context creation doesn't work for you for most case? Or are you speaking about replays of apitrace?

**Comment by petevine** [comment]
I've never managed to see an apitrace replay under `gl4es` (only mesa) but now `gl4es` operating normally got broken too.

**Comment by ptitSeb** [comment]
and you have a bad window in glxgears?
Can you post the detailled log (with the DEBUG macro defined in glx.c)

**Comment by ptitSeb** [comment]
I have just fixed a small mistake, but I don't think it will fix your issues.

**Comment by petevine** [comment]
As long as the regression is not fixed it's a general issue I believe. 

Apitrace could still be buggy or not like my system but that's the original problem :)

**Comment by ptitSeb** [comment]
Yep, I'm trying to fix the general "bad window" issue you have. But I don't reproduce it on my side, so it's tricky to fix.

**Comment by petevine** [comment]
On Wed, 09 Nov 2016 07:49:32 -0800
ptitSeb <notifications@github.com> wrote:

> Yep, I'm trying to fix the general "bad window" issue you have. But I don't reproduce it on my side, so it's tricky to fix.

I've just recompiled the latest revision and can't reproduce either. After reverting the last commit I can confirm that was it!

Back on topic: mesa is very slow, so I'm not sure if replaying a trace, like this:

`Rendered 1566 frames in 32.4838 secs, average of 48.2086 fps`

means it was trying to render as fast as possible or it just recreated the previously recorded framerates?

**Comment by ptitSeb** [comment]
I'm not sure either.
The trace you replayed was a complex game of just glxgears?

**Comment by ptitSeb** [comment]
Glad the "bad window" is fixed :)

**Comment by petevine** [comment]
Just glxgears, otherwise single digits would have been great! :)

**Comment by ptitSeb** [comment]
I don't undersand, where the trace was capture and where it was replayed.

**Comment by petevine** [comment]
Right now, I can only replay under mesa but not under gl4es - what do the numbers say on your machine? 
In other words, is the save format trying to preserve FPS or just replaying the calls full gas?

**Comment by petevine** [comment]
If it's the latter, the issue can be closed as that's exactly what I had in mind. A pity I won't be able to test gl4es myself :(

**Comment by ptitSeb** [comment]
Why you cannot test gl4es yourself? Because the replay doesn't work?

**Comment by ptitSeb** [comment]
Idealy, the record of the trace should be done on the same machine where the replay will be done, to avoid issue with unsupported extensions.
But I haven't succeed in recording SDL game with gl4es / apitrace. I think glxgears can be recorded, but I haven't tried replay yet.

**Comment by petevine** [comment]
Yeah, we've been going about it most of this thread. Then the `gl4es` regression happened later and was fixed subsequently but it never affected the apitrace problem.

**Comment by petevine** [comment]
Torcs can definitely be captured using mesa and maybe replayed under gl4es on your machine?

**Comment by ptitSeb** [comment]
For the testing, it would be interesting to have:
Torcs: pretty complex geometry, large textures
FooBillardPlus: Lots of TexGen, lots of glLists
yQuake2: fragmented drawing
Quake3 or SeriousSam: highly optimised renderer
SuperTuxKart: Very large textures
FreeOrion: complex functions

**Comment by petevine** [comment]
- using `gl4es`: `LIBGL_VSYNC=1 apitrace trace glxgears` -> 30 FPS
- using MESA: `apitrace replay glxgears.trace` -> 65.677 FPS

so it's definitely not a movie but a real benchmark! If you're interested in fixing torcs replay (no SDL) I can open a separate issue.

**Comment by ptitSeb** [comment]
Yes I'll try to fix it.

**Comment by petevine** [comment]
@ptitseb Cool, I've opened issue #14 
@lunixbochs Thanks for the apitrace idea! I hope gcc's codegen impact might be measurable too.

**Comment by lunixbochs** [comment]
I've fixed some EGL problems in upstream recently. You should try replaying glxgears into upstream glshim unstable. Which device are you on?

**Comment by petevine** [comment]
@lunixbochs I'm on this little [bugger](https://gist.github.com/petevine/c681e8613da9c4bb205c). 
Unfortunately `glshim` unstable doesn't work either:
````
$ apitrace replay glxgears.11.trace 
libGL:loaded: libGLESv1_CM.so
libGL:loaded: libEGL.so
libGL: built on Nov  9 2016 22:17:13
ERROR: EGL Error detected: EGL_BAD_NATIVE_WINDOW (0x300B)
ERROR: EGL Error detected: EGL_BAD_MATCH (0x3009)
error: failed to make current OpenGL context and drawable
````

**Comment by lunixbochs** [comment]
what is the name of the board you are using?

**Comment by petevine** [comment]
On Wed, 09 Nov 2016 13:38:36 -0800
Ryan Hileman <notifications@github.com> wrote:

> what is the name of the board you are using?

Odroid C1
