### ISSUE TITLE
SSam Emscripten glDrawElements failing

### ISSUE THREAD

**Issue by martinmullins** [ptitSeb/gl4es#254]
Thanks for your work on the Serious Sam Engine and Gl4ES! Im was able to get both running in the browser but Im getting weird scene rendering, which I am guessing is the attrib/index errors: `WebGL warning: drawElementsInstanced: Indexed vertex fetch requires XX vertices, but attribs only supply YY`

Here's a screen shot of what it looks like in Firefox:

![screenshot_ssam](https://user-images.githubusercontent.com/13143585/100660956-aa23c700-334a-11eb-9e03-c59b67c6e8d8.png)

Running natively it looks fine:
![image](https://user-images.githubusercontent.com/13143585/100664348-6089ab00-334f-11eb-9a5e-4cffec2a65d8.png)
 

I get these WebGL warnings on firefox:

```
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 8 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 12 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 16 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 36 vertices, but attribs only supply 26. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 46 vertices, but attribs only supply 26. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 8 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 8 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 8 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 12 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 16 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 52 vertices, but attribs only supply 32. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 60 vertices, but attribs only supply 26. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 74 vertices, but attribs only supply 32. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 92 vertices, but attribs only supply 64. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 8 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 12 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 16 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 20 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 24 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 28 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
Creating directory /SaveGame ... ssam-tfe:1237:21
Creating directory /SaveGame/Player0 ... ssam-tfe:1237:21
Creating directory /SaveGame/Player0/Quick ... ssam-tfe:1237:21
Saved game: SaveGame/Player0/Quick/QuickSave000000.sav ssam-tfe:1237:21
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 24 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
GL Error 'GL_INVALID_ENUM': UpdateDepthPointsVisibility():/home/marto/Serious-Engine/Sources/Engine/Graphics/DepthCheck.cpp:73 errno=1280 86 ssam-tfe:1237:21
WebGL warning: readPixels: Unexpected format or type. ssam-tfe.js:9958:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 24 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: readPixels: Unexpected format or type. ssam-tfe.js:9958:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 24 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL warning: readPixels: Unexpected format or type. ssam-tfe.js:9958:13
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 24 vertices, but attribs only supply 6. ssam-tfe.js:8645:13
WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings) ssam-tfe.js:8645:13
Request for pointer lock was denied because Element.requestPointerLock() was not called from inside a short running user-generated event handler, and the document is not in full screen. ssam-tfe
GL Error 'GL_INVALID_ENUM': UpdateDepthPointsVisibility():/home/marto/Serious-Engine/Sources/Engine/Graphics/DepthCheck.cpp:73 errno=1280 31 ssam-tfe:1237:21
Request for pointer lock was denied because the document is not focused. ssam-tfe.js:8070:15
GL Error 'GL_INVALID_ENUM': UpdateDepthPointsVisibility():/home/marto/Serious-Engine/Sources/Engine/Graphics/DepthCheck.cpp:73 errno=1280 281 ssam-tfe:1237:21
```

I've tried debugging the glDrawElements calls to find the cause, but have had no luck. Any ideas?

I found the message comes from Mozilla's webGL code here: https://searchfox.org/mozilla-central/source/dom/canvas/WebGLContextDraw.cpp#850

Also I've run the code with WebGL-Inspector here is the a couple of failing glDrawElement calls (the first glDrawElement call is fine): 
```
$x('//div[@class="trace-call-line"]').forEach(p => console.log(p.innerText))
bindTexture(TEXTURE_2D, [Texture 2]) debugger eval code:1:60
texSubImage2D(TEXTURE_2D, 0, 0, 0, 128, 1, LUMINANCE_ALPHA, UNSIGNED_BYTE, [255,0,255,6,255,13,255,19,255,25,255,31,255,37,255,43,255,49,255,54,255,59,255,65,255,70,255,75,255,79,255,84,255,88,255,93,255,97,255,101,255,105,255,109,255,113,255,117,255,120,255,124,255,127,255,131,255,134,255,137,255,140,255,143,,... (256 total)]) debugger eval code:1:60
finish() debugger eval code:1:60
depthMask(true) debugger eval code:1:60
clearDepth(1) debugger eval code:1:60
clear(DEPTH_BUFFER_BIT | STENCIL_BUFFER_BIT) debugger eval code:1:60
depthRange(0.8999999761581421, 1) debugger eval code:1:60
enable(CULL_FACE) debugger eval code:1:60
disable(CULL_FACE) debugger eval code:1:60
enable(DEPTH_TEST) debugger eval code:1:60
disable(BLEND) debugger eval code:1:60
bindTexture(TEXTURE_2D, [Texture 543]) debugger eval code:1:60
useProgram([Program 1118]) debugger eval code:1:60
uniformMatrix4fv("_gl4es_ModelViewProjectionMatrix", false, [1,0,0,0,0,1.3333333730697632,0,0,0,0,-1.0000050067901611,-1,0,0,-0.5000012516975403,0]) debugger eval code:1:60
bindBuffer(ELEMENT_ARRAY_BUFFER, [Buffer 289]) debugger eval code:1:60
bufferSubData(ELEMENT_ARRAY_BUFFER, 0, [0,0,1,0,2,0,0,0,2,0,3,0]) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 368]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [69,190,1,65,184,88,35,192,243,132,168,193,0,0,0,0,96,38,13,0,33,222,105,65,216,219,10,192,145,128,206,192,0,0,0,99,0,0,0,8,33,222,105,65,104,27,234,63,85,218,209,192,0,0,0,125,0,0,0,126,69,190,1,65,,... (120 total)]) debugger eval code:1:60
vertexAttribPointer(0, 3, FLOAT, false, 20, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 369]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]) debugger eval code:1:60
vertexAttribPointer(3, 4, UNSIGNED_BYTE, true, 4, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 370]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [0,0,128,177,253,255,127,63,0,0,128,63,252,255,127,63,0,0,128,63,0,0,172,180,245,230,195,48,139,233,127,180,0,0,32,49,1,0,128,63,0,0,128,63,1,0,128,63]) debugger eval code:1:60
vertexAttribPointer(8, 2, FLOAT, false, 8, 0) debugger eval code:1:60
drawElements(TRIANGLES, 6, UNSIGNED_SHORT, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, null) debugger eval code:1:60
bindBuffer(ELEMENT_ARRAY_BUFFER, null) debugger eval code:1:60
bindTexture(TEXTURE_2D, [Texture 539]) debugger eval code:1:60
bindBuffer(ELEMENT_ARRAY_BUFFER, [Buffer 289]) debugger eval code:1:60
bufferSubData(ELEMENT_ARRAY_BUFFER, 0, [4,0,5,0,6,0,7,0,6,0,5,0]) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 371]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [69,190,1,65,184,88,35,192,243,132,168,193,0,0,0,0,96,38,13,0,33,222,105,65,216,219,10,192,145,128,206,192,0,0,0,99,0,0,0,8,33,222,105,65,104,27,234,63,85,218,209,192,0,0,0,125,0,0,0,126,69,190,1,65,,... (120 total)]) debugger eval code:1:60
vertexAttribPointer(0, 3, FLOAT, false, 20, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 372]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]) debugger eval code:1:60
vertexAttribPointer(3, 4, UNSIGNED_BYTE, true, 4, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 373]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [0,0,128,177,253,255,127,63,0,0,128,63,252,255,127,63,0,0,128,63,0,0,172,180,245,230,195,48,139,233,127,180,0,0,32,49,1,0,128,63,0,0,128,63,1,0,128,63]) debugger eval code:1:60
vertexAttribPointer(8, 2, FLOAT, false, 8, 0) debugger eval code:1:60

>>>>>> INVALID_OPERATION at this call:
drawElements(TRIANGLES, 6, UNSIGNED_SHORT, 0) debugger eval code:1:60

bindBuffer(ARRAY_BUFFER, null) debugger eval code:1:60
bindBuffer(ELEMENT_ARRAY_BUFFER, null) debugger eval code:1:60
bindTexture(TEXTURE_2D, [Texture 537]) debugger eval code:1:60
bindBuffer(ELEMENT_ARRAY_BUFFER, [Buffer 289]) debugger eval code:1:60
bufferSubData(ELEMENT_ARRAY_BUFFER, 0, [8,0,9,0,10,0,8,0,10,0,11,0]) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 374]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [69,190,1,65,184,88,35,192,243,132,168,193,0,0,0,0,96,38,13,0,33,222,105,65,216,219,10,192,145,128,206,192,0,0,0,99,0,0,0,8,33,222,105,65,104,27,234,63,85,218,209,192,0,0,0,125,0,0,0,126,69,190,1,65,,... (120 total)]) debugger eval code:1:60
vertexAttribPointer(0, 3, FLOAT, false, 20, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 375]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]) debugger eval code:1:60
vertexAttribPointer(3, 4, UNSIGNED_BYTE, true, 4, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 376]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [0,0,128,177,253,255,127,63,0,0,128,63,252,255,127,63,0,0,128,63,0,0,172,180,245,230,195,48,139,233,127,180,0,0,32,49,1,0,128,63,0,0,128,63,1,0,128,63]) debugger eval code:1:60
vertexAttribPointer(8, 2, FLOAT, false, 8, 0) debugger eval code:1:60

>>>>>> INVALID_OPERATION at this call:
drawElements(TRIANGLES, 6, UNSIGNED_SHORT, 0) debugger eval code:1:60

bindBuffer(ARRAY_BUFFER, null) debugger eval code:1:60
bindBuffer(ELEMENT_ARRAY_BUFFER, null) debugger eval code:1:60
...........
```

**Comment by ptitSeb** [comment]
Nice project :D

About gl4es, do you use latest source, because I just fixed some issues with glDrawElements yesterday!

**Comment by martinmullins** [comment]
> Nice project :D
>

Thanks!

> About gl4es, do you use latest source, because I just fixed some issues with glDrawElements yesterday!

Unfortunately, just double checked with a clean rebuild and still have the same behaviour.

**Comment by ptitSeb** [comment]
This is strange, because in the debug you did, I see no trace of error:
```
bindBuffer(ELEMENT_ARRAY_BUFFER, [Buffer 289]) debugger eval code:1:60
bufferSubData(ELEMENT_ARRAY_BUFFER, 0, [0,0,1,0,2,0,0,0,2,0,3,0]) debugger eval code:1:60
```
Here ^^^ the ELEMENT_ARRAY_BUFFER 289 is setup with 6 short (so 12 bytes)
```
bindBuffer(ARRAY_BUFFER, [Buffer 368]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [69,190,1,65,184,88,35,192,243,132,168,193,0,0,0,0,96,38,13,0,33,222,105,65,216,219,10,192,145,128,206,192,0,0,0,99,0,0,0,8,33,222,105,65,104,27,234,63,85,218,209,192,0,0,0,125,0,0,0,126,69,190,1,65,,... (120 total)]) debugger eval code:1:60
vertexAttribPointer(0, 3, FLOAT, false, 20, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 369]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]) debugger eval code:1:60
vertexAttribPointer(3, 4, UNSIGNED_BYTE, true, 4, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 370]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [0,0,128,177,253,255,127,63,0,0,128,63,252,255,127,63,0,0,128,63,0,0,172,180,245,230,195,48,139,233,127,180,0,0,32,49,1,0,128,63,0,0,128,63,1,0,128,63]) debugger eval code:1:60
vertexAttribPointer(8, 2, FLOAT, false, 8, 0) debugger eval code:1:60
drawElements(TRIANGLES, 6, UNSIGNED_SHORT, 0) debugger eval code:1:60
```
Here ^^^ drawing the 6 triangles with the index buffer of 6 shorts
```
bindBuffer(ARRAY_BUFFER, null) debugger eval code:1:60
bindBuffer(ELEMENT_ARRAY_BUFFER, null) debugger eval code:1:60
bindTexture(TEXTURE_2D, [Texture 539]) debugger eval code:1:60
bindBuffer(ELEMENT_ARRAY_BUFFER, [Buffer 289]) debugger eval code:1:60
bufferSubData(ELEMENT_ARRAY_BUFFER, 0, [4,0,5,0,6,0,7,0,6,0,5,0]) debugger eval code:1:60
```
Here ^^^ buffer 289 is setup with 6 short again
```
bindBuffer(ARRAY_BUFFER, [Buffer 371]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [69,190,1,65,184,88,35,192,243,132,168,193,0,0,0,0,96,38,13,0,33,222,105,65,216,219,10,192,145,128,206,192,0,0,0,99,0,0,0,8,33,222,105,65,104,27,234,63,85,218,209,192,0,0,0,125,0,0,0,126,69,190,1,65,,... (120 total)]) debugger eval code:1:60
vertexAttribPointer(0, 3, FLOAT, false, 20, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 372]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]) debugger eval code:1:60
vertexAttribPointer(3, 4, UNSIGNED_BYTE, true, 4, 0) debugger eval code:1:60
bindBuffer(ARRAY_BUFFER, [Buffer 373]) debugger eval code:1:60
bufferSubData(ARRAY_BUFFER, 0, [0,0,128,177,253,255,127,63,0,0,128,63,252,255,127,63,0,0,128,63,0,0,172,180,245,230,195,48,139,233,127,180,0,0,32,49,1,0,128,63,0,0,128,63,1,0,128,63]) debugger eval code:1:60
vertexAttribPointer(8, 2, FLOAT, false, 8, 0) debugger eval code:1:60

>>>>>> INVALID_OPERATION at this call:
drawElements(TRIANGLES, 6, UNSIGNED_SHORT, 0) debugger eval code:1:60
```
Here the draw is again of 6 triangles, so using 6 short...

It looks like there is a buggy optimisation there. Like the driver doesn't actually draw the drawElements, but accumulate the triangles (if you look at the error, the needed index is growing) until a change state force it to draw, but the acculation have forgotten the ELEMENT_ARRAY_BUFFER... Maybe it's Firefox itself that is buggy?

**Comment by martinmullins** [comment]
Thanks for taking a look! The issue ended up with emscripten's OpenGL ES -> WebGL emulation not using the correct length for the VertexAttrib buffers. 

The emulation javascript code is using the `count` argument passed to `glDrawElements` to determine the buffer lengths. 

In the trace above that length is fine for the first call to `glDrawElements(count=6)` but the next two calls have indices in the `ELEMENT_ARRAY_BUGGER` that are `>=6` so the calls will fail.

I just put in a temporary hack to fix this and it solved the glitches.

![image](https://user-images.githubusercontent.com/13143585/100796511-afe7de00-3418-11eb-843e-07026297781b.png)

There are other issues I need to go through, but it is looking much better!!

**Comment by ptitSeb** [comment]
Ah yes looking much better!
