### ISSUE TITLE
OpemMW - problems with textures on 1.1.4 and higher.

### ISSUE THREAD

**Issue by docent27** [ptitSeb/gl4es#279]
Some textures do not look correct on library version 1.1.4 and higher. Everything works fine on version 1.1.2.
This problem exists on any version of openmw, both the old 0.46 and the most recent 0.47.

This is what the wall texture looks like in library 1.1.2:
![1 1 2](https://user-images.githubusercontent.com/62644972/107628255-0bc8b180-6c69-11eb-83e4-19b7e1eb2fd9.jpg)

This is what the wall texture looks like in library 1.1.4 (and newer):
![1 1 4](https://user-images.githubusercontent.com/62644972/107628365-3581d880-6c69-11eb-83cb-62aacc1ab14e.jpg)

**Comment by ptitSeb** [comment]
So, it's some kind of gamma issue? How do you know wich version is correct?

**Comment by docent27** [comment]
Open the picture to full screen. In version 1.1.2 it is filtered, and in version 1.1.4 it is pixelated.

**Comment by pulion** [comment]
indeed, when using vanilla textures, in some cases the texture looks like a cluster of pixels.

**Comment by akortunov** [comment]
Is this issue fixed by referenced commit?

**Comment by docent27** [comment]
I can't answer this question yet, as openmw breaks on a new nightly build.

**Comment by docent27** [comment]
Texture issue not fixed.

![image](https://user-images.githubusercontent.com/62644972/110770254-c85e6480-8261-11eb-9a44-f39939a047f1.png)
