### ISSUE TITLE
In retroarch text is not correctly rendered

### ISSUE THREAD

**Issue by Icenowy** [ptitSeb/gl4es#35]
I'm trying to run retroarch on gl4es on Mesa libGLESv2.

The following error message appeared:
```
Mesa 17.1.4 implementation error: Unexpected incomplete framebuffer in _mesa_meta_GenerateMipmap()
Please report at https://bugs.freedesktop.org/enter_bug.cgi?product=Mesa
```

**Comment by ptitSeb** [comment]
I'll have a look in my dev machine. Incomplete framebuffer sounds bad.

**Comment by Icenowy** [comment]
[trace.zip](https://github.com/ptitSeb/gl4es/files/1410845/trace.zip)

Here's the GL api trace, which can produce correct image with Mesa GL, and broken with GL4ES.

**Comment by ptitSeb** [comment]
Ah nice, thanks !

**Comment by ptitSeb** [comment]
I don't reproduce a crash. But I fixed a couple of things in glX, and added some support to the built-in Derivatives functions.
Still the rendering I get is not correct...

**Comment by Icenowy** [comment]
It's not a crash, just bunch of error messages on my HD3000.

**Comment by Icenowy** [comment]
when I force LIBGL_MIPMAP=3 (no mipmap at all) the gears are able to be rendered, but the text is still not rendered properly.

**Comment by ptitSeb** [comment]
Ok.
So there is two issues.
I don't reproduce the issue with the gear, but I'll look at how there are rendered.

I do reproduce the issues with the text.

**Comment by Icenowy** [comment]
Commit 44d1ded880b791b3e0b884534b1bd2235bf0d318 solved the gear issue.

Text issue is not solved yet.

**Comment by ptitSeb** [comment]
Ah, nice side effect! I didn't expected that.

I will look at how text is render.

**Comment by ptitSeb** [comment]
Should be fixed with 5b210f94ce55696dce2f5455a4fef927b336a880

**Comment by Icenowy** [comment]
Fixed, thanks!
